# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirplaneTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_town', models.CharField(max_length=1024, verbose_name='Source Town')),
                ('dst_town', models.CharField(max_length=1024, verbose_name='Destination Town')),
                ('flight_no', models.IntegerField()),
                ('fi', models.IntegerField()),
                ('dispatch_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='BusTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_town', models.CharField(max_length=1024, verbose_name='Source Town')),
                ('dst_town', models.CharField(max_length=1024, verbose_name='Destination Town')),
                ('fi', models.IntegerField()),
                ('dispatch_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TrainTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_town', models.CharField(max_length=1024, verbose_name='Source Town')),
                ('dst_town', models.CharField(max_length=1024, verbose_name='Destination Town')),
                ('fi', models.IntegerField()),
                ('dispatch_time', models.DateTimeField()),
            ],
        ),
    ]
